### ISSUE TITLE
module startsWith is not a function

### ISSUE THREAD

**Issue by furstenheim** [m31271n/require-no-cache#1]
I'm trying to use the library in Node 4+ but I get the following error:

`require-no-cache/index.js:8
  if (module.startsWith('./') || module.startsWith('../')) {`
TypeError: module.startsWith is not a function

**Comment by m31271n** [comment]
`startsWith()`  is defined in ES6. And it's available from Node 5+, I guess. You can make a PR via [string.prototype.startswith](https://www.npmjs.com/package/string.prototype.startswith) .

**Comment by m31271n** [comment]
If you just wanna a useful module without PR, try the similiar things in `README.md`.

**Comment by furstenheim** [comment]
My bad, there is no error in Node 4

**Comment by m31271n** [comment]
😄
